# Generated by Django 5.0.3 on 2025-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(
                choices=[
                    ('BMI', 'BMI'),
                    ('SEP', 'SEP'),
                    ('ZARINPAL', 'Zarinpal'),
                    ('IDPAY', 'IDPay'),
                    ('ZIBAL', 'Zibal'),
                    ('BAHAMTA', 'Bahamta'),
                    ('MELLAT', 'Mellat'),
                    ('PAYV1', 'PayV1'),
                    ('SEPEHR', 'Sepehr'),
                    ('PEC', 'Parsian')
                ],
                max_length=50,
                verbose_name='Bank',
            ),
        ),
        migrations.AddField(
            model_name='bank',
            name='card_hash_number',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Card hash number',
            ),
        ),
    ]
